baseURL = 'https://devdocs.mcenahle.page/'
locale = 'zh-CN'
title = 'Dev Docs Website'
theme = 'hugo-book'

copyright = "Mcenahle website proj."
enableEmoji = true

disablePathToLower = true
enableGitInfo = true

[params]
  BookSection = 'docs'
  BookTheme = 'auto'
  BookSearch = true
  BookComments = false
  BookDateFormat = '2006-01-02'
  BookRepo = 'https://github.com/mcenahle/dev-docs'
  BookLastChangeLink = '{{ .Site.Params.BookRepo }}/commit/{{ .GitInfo.Hash }}'
  BookEditLink = '{{ .Site.Params.BookRepo }}/edit/main/{{ .Path }}'

defaultContentLanguage = "zh"
defaultContentLanguageInSubdir = false

[languages.zh]
locale = "简体中文"
label = "zh-CN"
weight = 1